---
apiVersion: v2
name: mu
description: mu application
type: application
version: 0.0.8
appVersion: 8f6f6f145a1c8a78ee1a4fd410e4e71f239a3f9a
dependencies:
  - alias: mu
    name: app
    version: 0.0.8
    repository: oci://public.ecr.aws/andreswebs/charts
