---
apiVersion: v2
name: mu
description: mu application
type: application
version: 0.0.8
appVersion: 198a5cfc06c14c59e9685f057f54e36ad49741cb
dependencies:
  - alias: mu
    name: app
    version: 0.0.8
    repository: oci://public.ecr.aws/andreswebs/charts
