---
apiVersion: v2
name: mu
description: mu application
type: application
version: 0.0.8
appVersion: fc846a68b4852fbda7f29836a0910ce820cce202
dependencies:
  - alias: mu
    name: app
    version: 0.0.8
    repository: oci://public.ecr.aws/andreswebs/charts
