---
apiVersion: v2
name: mu
description: mu application
type: application
version: 0.0.8
appVersion: 93d5fbc50fecab3d89903e06dd4afaa889acd4f6
dependencies:
  - alias: mu
    name: app
    version: 0.0.8
    repository: oci://public.ecr.aws/andreswebs/charts
